- hosts: all
  #vars:
  remote_user: centos
  become: yes
  #rolling upgrade
  serial: 1
  become_method: sudo
  tasks:
  - name: stop services
    shell: sleep 30
  
  - Add CentOS Base Yum repo 
    yum_repository:
      name: CentOS-$releasever - Base
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
      gpgcheck: yes
      enabled: yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

  - Add CentOS Updates Yum repo
    yum_repository:
      name: CentOS-$releasever - Updates
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra
      gpgcheck: yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

  - Add CentOS Extras Yum repo
    yum_repository:
      name: CentOS-$releasever - Extras
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra
      gpgcheck: yes
      enabled: yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

  - Add CentOS Plus Yum repo      
    yum_repository:
      name: CentOS-$releasever - Plus
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus&infra=$infra
      gpgcheck: yes
      enabled: yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

  - name: Upgrade Nginx 
    yum: name=nginx state=latest
    sudo: true

  - name: Start nginx 
    service: name=nginx state=restarted
    sudo: true

  - name: another task
    shell: sleep 30
